from conans import ConanFile, CMake, tools
from conans.client.tools.pkg_config import PkgConfig
from conans.errors import ConanInvalidConfiguration
import os

class OSDialogConan(ConanFile):
    name = "OSDialog"
    version = "latest"
    license = "CC0"
    author = "Andrew Belt"
    url = "https://github.com/qno/conan-osdialog"
    homepage = "https://github.com/AndrewBelt/osdialog"
    description = "A cross platform wrapper for OS dialogs like file save, open, message boxes, inputs, color picking, etc."

    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"

    options = {
        "shared": [True, False],
        "fPIC": [True, False]
        }
    default_options = {
        "shared": False,
         "fPIC": True
         }

    _pkg_name = "osdialog-master"
    _libname = "osdialog"

    def system_requirements(self):
        if tools.os_info.is_linux:
            if tools.os_info.with_apt:
                installer = tools.SystemPackageTool()
                if self.settings.arch == "x86" and tools.detected_architecture() == "x86_64":
                    arch_suffix = ':i386'
                    installer.install("g++-multilib")
                else:
                    arch_suffix = ''
                installer.install("{}{}".format("libgtk2.0-dev", arch_suffix))
                installer.install("{}{}".format("libgtk-3-dev", arch_suffix))
            elif tools.os_info.with_yum:
                installer = tools.SystemPackageTool()
                if self.settings.arch == "x86" and tools.detected_architecture() == "x86_64":
                    arch_suffix = '.i686'
                else:
                    arch_suffix = ''
                installer.install("{}{}".format("gtk2-devel", arch_suffix))
                installer.install("{}{}".format("gtk3-devel", arch_suffix))
            elif tools.os_info.with_pacman:
                if self.settings.arch == "x86" and tools.detected_architecture() == "x86_64":
                    # Note: The packages with the "lib32-" prefix will only be
                    # available if the user has activate Arch's multilib
                    # repository, See
                    # https://wiki.archlinux.org/index.php/official_repositories#multilib
                    arch_suffix = 'lib32-'
                else:
                    arch_suffix = ''
                installer = tools.SystemPackageTool()
                installer.install("{}{}".format(arch_suffix, "gtk2"))
                installer.install("{}{}".format(arch_suffix, "gtk3"))
            else:
                self.output.warn("Could not determine package manager, skipping Linux system requirements installation.")

    def source(self):
        url = "https://github.com/AndrewBelt/osdialog/archive/master.zip"
        self.output.info("Downloading {}".format(url))
        tools.get(url)
        self._createCMakeLists()

    def configure(self):
        del self.settings.compiler.libcxx
        del self.options.fPIC
        if self.options.shared:
            raise ConanInvalidConfiguration("This library doesn't support shared lib compilation")

    def build(self):
        cmake = CMake(self)
        cmake.configure(source_dir=self._pkg_name)
        cmake.build()

    def package(self):
        self.copy("*.h", dst="include", src=self._pkg_name)
        self.copy("*.lib", dst="lib", keep_path=False)
        self.copy("*.dll", dst="lib", keep_path=False)
        self.copy("*.so", dst="lib", keep_path=False)
        self.copy("*.dylib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = [self._libname]

        if self.settings.os == "Linux":
            pkg_config = PkgConfig("gtk+-3.0")
            for lib in pkg_config.libs_only_l:
                self.cpp_info.libs.append(lib[2:])

        if self.settings.os == "Windows":
            self.cpp_info.libs.append("comdlg32")

        if self.settings.os == "Macos":
            self.cpp_info.exelinkflags.append("-framework AppKit")

    def _isVisualStudioBuild(self):
        return self.settings.os == "Windows" and self.settings.compiler == "Visual Studio"

    def _createCMakeLists(self):
        content = '''\
# THIS FILE WAS GENERATED BY CONAN RECIPE. DO NOT EDIT THIS FILE!
cmake_minimum_required(VERSION 3.5)
project(OSDialog)

set (CMAKE_C_STANDARD 11)

include(${{CMAKE_BINARY_DIR}}/conanbuildinfo.cmake)
conan_basic_setup()

set(LIBOSDIALOG "{}")

if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
   set(PLATFORM_SOURCE osdialog_win.c)
elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
   set(PLATFORM_SOURCE osdialog_gtk3.c)
elseif (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
   set(PLATFORM_SOURCE osdialog_mac.m)
else ()
   message(FATAL_ERROR "This platform '${{CMAKE_SYSTEM_NAME}}'is not supported by this library")
endif ()

set(SOURCES osdialog.c ${{PLATFORM_SOURCE}})

add_library(${{LIBOSDIALOG}} ${{SOURCES}})

if (CMAKE_SYSTEM_NAME STREQUAL "Linux")
   find_package(GTK3 REQUIRED)
   target_include_directories(${{LIBOSDIALOG}} PRIVATE ${{GTK3_INCLUDE_DIRS}})
   target_compile_definitions(${{LIBOSDIALOG}} PRIVATE GTK3_DEFINITIONS)
   target_link_libraries(${{LIBOSDIALOG}} PRIVATE ${{GTK3_LIBRARIES}})
endif ()

if (MSVC)
   target_compile_options(${{LIBOSDIALOG}} PRIVATE /Wall)
else ()
   target_compile_options(${{LIBOSDIALOG}} PRIVATE -Wall -Wextra -pedantic)
endif ()
'''.format(self._libname)

        self.output.info("create CMakeLists.txt file")
        cmake_file = os.path.join(self._pkg_name, "CMakeLists.txt")
        f = open(cmake_file, "w+")
        f.write(content)
        f.close()
